name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-cml:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Get Project ID
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJ_NAME: "cicd-demo"
        run: |
          PROJECT_ID=$(curl -X GET "$CDSW_DOMAIN/api/v2/projects?search_filter=%7B%22name%22%3A%22$PROJ_NAME%22%7D" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" | jq -r ".projects|.[0]|.id")
          echo "Project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

  data-ingest:
    runs-on: ubuntu-latest
    needs: deploy-to-cml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Data Ingestion
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          JOB_ID=$(curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"environment": "python3.9", "spark": true, "cpu": 2, "memory": 4, "script": "code/1_data_ingest.py"}' | jq -r ".id")
          curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs/$JOB_ID/runs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json"

  eda:
    runs-on: ubuntu-latest
    needs: data-ingest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run EDA Notebook
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          JOB_ID=$(curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"environment": "jupyter", "spark": true, "cpu": 2, "memory": 4, "notebook": "code/2_data_exploration.ipynb"}' | jq -r ".id")
          curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs/$JOB_ID/runs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json"

  model-training:
    runs-on: ubuntu-latest
    needs: eda
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Model Training
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          JOB_ID=$(curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"environment": "jupyter", "spark": true, "cpu": 2, "memory": 4, "notebook": "code/4_train_models.ipynb"}' | jq -r ".id")
          curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs/$JOB_ID/runs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json"

  create-experiment:
    runs-on: ubuntu-latest
    needs: model-training
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Experiment Script
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          JOB_ID=$(curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"environment": "python3.9", "spark": true, "cpu": 2, "memory": 4, "script": "code/4_train_model.py"}' | jq -r ".id")
          curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/jobs/$JOB_ID/runs" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json"

  deploy:
    runs-on: ubuntu-latest
    needs: create-experiment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Model
        env:
          API_KEY: ${{ secrets.CML_API_KEY }}
          CDSW_DOMAIN: "https://your-cml-url"
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          curl -X POST "$CDSW_DOMAIN/api/v2/projects/$PROJECT_ID/models" \
          -H "accept: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"model_name": "Churn Model API Endpoint", "file_name": "code/5_model_serve_explainer.py", "function": "explain", "runtime": "python3.9", "spark": true}'
